// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjJiCW2qbDXgM0KDnqcRAKhOxk43QsQnM',
    appId: '1:482046058527:web:de26803b998bbbc1b3f52a',
    messagingSenderId: '482046058527',
    projectId: 'hostel-complaint-system-4a8a5',
    authDomain: 'hostel-complaint-system-4a8a5.firebaseapp.com',
    storageBucket: 'hostel-complaint-system-4a8a5.firebasestorage.app',
    measurementId: 'G-6W8LKVF725',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7u4Og1XRMdRWJY__KXBjSW-9YSdF5XTA',
    appId: '1:482046058527:android:edbcb52783c56648b3f52a',
    messagingSenderId: '482046058527',
    projectId: 'hostel-complaint-system-4a8a5',
    storageBucket: 'hostel-complaint-system-4a8a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-puZstXj0iDixNUD-a1BnBmP4V67P81Y',
    appId: '1:482046058527:ios:b38065e0bc4cba77b3f52a',
    messagingSenderId: '482046058527',
    projectId: 'hostel-complaint-system-4a8a5',
    storageBucket: 'hostel-complaint-system-4a8a5.firebasestorage.app',
    iosBundleId: 'com.example.hostelComplaintApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-puZstXj0iDixNUD-a1BnBmP4V67P81Y',
    appId: '1:482046058527:ios:b38065e0bc4cba77b3f52a',
    messagingSenderId: '482046058527',
    projectId: 'hostel-complaint-system-4a8a5',
    storageBucket: 'hostel-complaint-system-4a8a5.firebasestorage.app',
    iosBundleId: 'com.example.hostelComplaintApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjJiCW2qbDXgM0KDnqcRAKhOxk43QsQnM',
    appId: '1:482046058527:web:061f749a08ee8e67b3f52a',
    messagingSenderId: '482046058527',
    projectId: 'hostel-complaint-system-4a8a5',
    authDomain: 'hostel-complaint-system-4a8a5.firebaseapp.com',
    storageBucket: 'hostel-complaint-system-4a8a5.firebasestorage.app',
    measurementId: 'G-WP9DDKLSQZ',
  );
}
